### ISSUE TITLE
[BUG] Recent Uploads tab in Profile page always keep loading

### ISSUE THREAD

**Issue by kiranofans** [WikiEducationFoundation/apps-android-wikiedudashboard#237] opened 2019-11-07 22:01 UTC
### This issue has been fixed after the pull request #242 and #247 have been merged
================================
**Summary:** 
Recent Uploads tab in Profile page always keep loading, seems never stop

**Steps to reproduce:** 
Go to Profile -> tap Recent Uploads -> the page keeps loading...

**System logs:**

```
2019-11-07 13:59:41.515 20823-20823/? D/ViewRootImpl@8868798[HomeActivity]: ViewPostImeInputStage processPointer 0
2019-11-07 13:59:41.588 20823-20823/? D/ViewRootImpl@8868798[HomeActivity]: ViewPostImeInputStage processPointer 1
2019-11-07 13:59:41.596 20823-20823/? D/LeakCanary: Watching instance of android.widget.ScrollView with key 57664f4e-b93c-43ef-a454-6a20cb7d22c3
2019-11-07 13:58:59.238 20823-20842/? D/LeakCanary: Checking retained instances because Showing retained instance notification
2019-11-07 13:58:59.238 20823-20842/? D/LeakCanary: Found 2 retained instances, which is less than the visible threshold of 5
2019-11-07 13:58:59.388 20823-20842/? D/LeakCanary: Checking retained instances because Showing retained instance notification
2019-11-07 13:58:59.388 20823-20842/? D/LeakCanary: Found 2 retained instances, which is less than the visible threshold of 5
2019-11-18 21:29:12.202 19846-19853/org.wikiedufoundation.wikiedudashboard.release I/art: Debugger is no longer active
2019-11-18 21:29:12.202 19846-19853/org.wikiedufoundation.wikiedudashboard.release I/art: Starting a blocking GC Instrumentation
```

**Device and Android version:** 
Samsung Galaxy Tablet A, Android 7.1
 
**Would you like to work on the issue?**
No

The progress bar on the Recent Uploads page keeps loading, and I'm not sure how to debug this issue. 
I tried to add some breakpoints around the `view.showProgressbar(true)` and ran the app, the app doesn't break at the breakpoints. just saw the error saying `Debugger is no longer active`

**Comment by ujjwalagrawal17** [comment] 2019-12-15 22:43
As the issue is fixed. I am closing this PR. Thanks for creating the issue.

**Closed by ujjwalagrawal17** 2019-12-15 22:43 UTC
Labels: bug
