### ISSUE TITLE
[BUG] App Crashes onclick upload list item

### ISSUE THREAD

**Issue by gconnect** [WikiEducationFoundation/apps-android-wikiedudashboard#267] opened 2019-12-08 23:14 UTC
**App Crashes onclick upload list item** 

When the **Upload** tab list item is clicked the app crashes

**Steps to reproduce:** 

- Allow the app to crash and check the log for error for possible cause of the crash
- Fix the crash

**System logs:**

```
Add logcat files here (if possible).

```
![image](https://user-images.githubusercontent.com/23031920/70398151-d26b3500-1a18-11ea-8d7a-cf747ac4c8f1.png)

**Device and Android version:** 

I encountered this on Infinix Hot 6X Android 8.1
 
**Screen-shots:** 
![image](https://user-images.githubusercontent.com/23031920/70398158-df882400-1a18-11ea-83bb-a152b5abc39e.png)

**Would you like to work on the issue?**

Yes

**Comment by ujjwalagrawal17** [comment] 2019-12-10 13:47
Thanks for creating the issue. It seems  like it is duplicate of #220 so closing this.

**Closed by ujjwalagrawal17** 2019-12-10 13:47 UTC
Labels: bug, outreachy-round-19
