### ISSUE TITLE
[BUG] App Crashed At Launching

### ISSUE THREAD

**Issue by kiranofans** [WikiEducationFoundation/apps-android-wikiedudashboard#96] opened 2019-10-05 22:36 UTC
**Summary:** 

The App crashed at launching after tried to login to .Outreach Programs and Events

**Steps to reproduce:** 

1. Install the app using Android studio or download from google play store
2. Open the app -> login with Wikipedia to Outreach Programs and Events
3. Logged in successfully -> allowed Oauth -> Some content showed up and then the app crashed
4. Open the app again -> it crashed at launching

**System logs:**

```
10-05 15:49:31.308 2783-2783/org.wikiedufoundation.wikiedudashboard.release E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 2783
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wikiedufoundation.wikiedudashboard.release/org.wikiedufoundation.wikiedudashboard.ui.home.HomeActivity}: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at org.wikiedufoundation.wikiedudashboard.ui.home.HomeActivity.onCreate(HomeActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:6285)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at org.wikiedufoundation.wikiedudashboard.ui.home.HomeActivity.onCreate(HomeActivity.kt:28) 
        at android.app.Activity.performCreate(Activity.java:6285) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at org.wikiedufoundation.wikiedudashboard.ui.home.HomeActivity.onCreate(HomeActivity.kt:28) 
        at android.app.Activity.performCreate(Activity.java:6285) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f07006c
        at android.content.res.Resources.getValue(Resources.java:1358)
        at androidx.appcompat.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:331)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
        at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.initialize(BottomNavigationItemView.java:105)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:523)
        at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)
        at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:254)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:187)
    	at com.google.android.material.bottomnavigation.BottomNaviga
```  

**Device and Android version:** 
Testing device: Sony Xperia Z3, android 6.0 Marshmallow

**Would you like to work on the issue?**
No

**Comment by MarinaTaran** [comment] 2019-10-06 06:04
Hello. Can I try to do this?

**Comment by ujjwalagrawal17** [comment] 2019-10-06 12:49
I am unable to reproduce this in Pixel 3 API 25.

@MarinaTaran are you able to reproduce the issue? If yes, you can start working on it.

**Comment by MarinaTaran** [comment] 2019-10-06 14:45
![Screenshot_1570372807](https://user-images.githubusercontent.com/42735198/66270859-c28c7480-e860-11e9-9f07-64651e43d3a1.png)
I installed Pixel 3 API 25.
what should I push here to continue?

**Comment by ujjwalagrawal17** [comment] 2019-10-06 14:52
You can allow and check if app is working properly or crashing.

**Comment by ujjwalagrawal17** [comment] 2019-10-06 14:53
@kirofans are you able to reproduce this on current master branch ?

**Comment by MarinaTaran** [comment] 2019-10-06 15:07
![Screenshot_1570374404](https://user-images.githubusercontent.com/42735198/66271225-28c6c680-e864-11e9-8f71-8d3d56c128be.png)

**Comment by kiranofans** [comment] 2019-10-06 17:03
@ujjwalagrawal17 I tried several times. Both from google play and installed from studio. Download the app from google play, I swipped to left to login to outreach program and event, allow oauth and I still got the crash

**Comment by ujjwalagrawal17** [comment] 2019-10-06 18:09
Okay. If you are able to reproduce the issue and are interested in solving this, a PR to fix the issue will be appreciated.

**Comment by MarinaTaran** [comment] 2019-10-06 19:01
I saw such a solution for this problem:
  instead:
app:itemBackground="?colorPrimary"
to write
app:itemBackground="@color/colorPrimary"
And I saw at your code once you write:
android:background="?attr/colorPrimary"
and once
android:background="@color/colorGrayBackground"
maybe you should try to write as it is written in the second case
android:background="@color/colorPrimary"

One more solution maybe you can try : some one faced this issue  and it was because the android:textAppearance attribute was missing.
Just add the below attribute and your problem should be fixed.
android:textAppearance="@style/TextAppearance.MaterialComponents.Button"

**Comment by kiranofans** [comment] 2019-10-06 22:04
@MarinaTaran Do you mean to add the line to app_bar_main.xml?
the code I have now for the app_bar_main.xml is: 
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.home.HomeActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:layout_constraintTop_toTopOf="@+id/home_container"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:title="@string/title_dashboard"
            app:titleTextColor="@color/black" />

    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
        android:id="@+id/home_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bottom_nav_view"
        android:layout_below="@+id/appBarLayout"
        android:background="@color/colorGrayBackground"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/appBarLayout">

    </FrameLayout>

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_nav_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="?android:attr/windowBackground"
        app:itemIconTint="@color/bottom_nav_color"
        app:itemTextColor="@color/bottom_nav_color"
        app:layout_constraintBottom_toBottomOf="@+id/home_container"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_nav_menu" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by MarinaTaran** [comment] 2019-10-07 06:46
Yes,I tried also it doesn't work. But there are not just one issue:
android:textAppearance="@style/TextAppearance.MaterialComponents.Button" this is was just about this issue:### Caused by: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:53 and this is in line 36 maybe this  attribute in this layout  introduce at a higher level of API than we have

### Caused by: java.lang.reflect.InvocationTargetException

###  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f07006c  about this issue maybe we can check together :There is issue related resources.It'll tell you which resource was creating problem. android.content.res. Resources$NotFoundException: Resource ID #0x7f02004f.
It might happen if you are trying to setText int value instead of String or  resource file in drawable-21 folder and it looking into the drawable folder[Just put the resource into drawable folder]. For now I didn't find?

**Comment by MarinaTaran** [comment] 2019-10-07 07:59
![20191007_105404 (2)](https://user-images.githubusercontent.com/42735198/66294365-7dfce980-e8f1-11e9-8083-c9684be308fd.jpg)
   look at this

**Comment by MarinaTaran** [comment] 2019-10-07 08:02
@ujjwalagrawal17

**Closed** 2019-10-08 20:01 UTC
Labels: bug, good first issue
